#!/usr/bin/env bash
# 配布アプリに含まれる第三者コンポーネントのライセンス本文を
# Resources/Licenses/THIRD_PARTY_LICENSES.txt に生成する。
#
# 対象:
#   - MahoCrawl 本体 (src-tauri) の Rust 依存クレート
#   - 同梱 SiteOne Crawler（パッチ適用済み chromiumoxide を含む）の Rust 依存クレート
#   - Chrome DevTools Protocol 定義（Chromium）
#   - フロントエンドの本番 npm 依存
#
# 前提: cargo-about (cargo install cargo-about --locked --features cli)、
#       npm install 済み、npm run build:siteone で .siteone-build が作成済み。
set -euo pipefail

project_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
config_dir="$project_root/scripts/third-party-licenses"
build_root="${SITEONE_BUILD_ROOT:-$project_root/.siteone-build}"
siteone_manifest="$build_root/siteone-crawler/Cargo.toml"
output="$project_root/Resources/Licenses/THIRD_PARTY_LICENSES.txt"

if ! cargo about --version >/dev/null 2>&1; then
  printf 'cargo-about が見つかりません: cargo install cargo-about --locked --features cli\n' >&2
  exit 1
fi
if [[ ! -f "$siteone_manifest" ]]; then
  printf 'SiteOne のビルドディレクトリが見つかりません。先に npm run build:siteone を実行してください: %s\n' "$siteone_manifest" >&2
  exit 1
fi

generate_rust_section() {
  local title="$1"
  local manifest="$2"
  printf '================================================================================\n'
  printf '%s\n' "$title"
  printf '================================================================================\n\n'
  cargo about generate \
    --config "$config_dir/about.toml" \
    --manifest-path "$manifest" \
    --fail \
    "$config_dir/about.hbs"
}

tmp_output="$(mktemp)"
trap 'rm -f "$tmp_output"' EXIT

{
  cat <<'EOF'
MahoCrawl Third-Party Licenses
==============================

This file lists the licenses of third-party software bundled in MahoCrawl.
It is generated by scripts/generate-third-party-licenses.sh.

Crates licensed under MPL-2.0 are used without modification. Their source
code is available from the repository URL listed next to each crate.

EOF
  generate_rust_section "Rust crates linked into MahoCrawl" "$project_root/src-tauri/Cargo.toml"
  generate_rust_section "Rust crates linked into the bundled SiteOne Crawler" "$siteone_manifest"

  printf '================================================================================\n'
  printf 'Chrome DevTools Protocol definitions (used by chromiumoxide)\n'
  printf '================================================================================\n\n'
  printf 'Source: https://github.com/ChromeDevTools/devtools-protocol\n\n'
  cat "$config_dir/chromium-devtools-protocol-LICENSE.txt"
  printf '\n'

  printf '================================================================================\n'
  printf 'npm packages bundled into the MahoCrawl frontend\n'
  printf '================================================================================\n\n'
  node "$config_dir/npm-licenses.mjs" "$project_root"
} >"$tmp_output"

mkdir -p "$(dirname "$output")"
mv "$tmp_output" "$output"
trap - EXIT

printf '第三者ライセンスを生成しました: %s\n' "$output"
